#!/bin/bash
#
# ~#KVERS:: v9.0.0.0 Copyright © 2007-2015 Kaseya International Limited. All Rights Reserved.
#

SYSVER=`sw_vers -productVersion | awk -F'.' '{print $1"."$2}'`

if [ $SYSVER = 10.0 -o $SYSVER = 10.1 -o $SYSVER = 10.2 -o $SYSVER = 10.3 -o $SYSVER = 10.4 ]; then
	echo "cannot unregister KUsrTsk from login for this system"
else
	echo "unregistering KUsrTsk from login"
	/var/tmp/RegisterKUsrTsk -r

	rm /var/tmp/RegisterKUsrTsk
fi

echo "Kaseya Uninstall Completed"
date >> /var/tmp/KasUninstall.log
